### ISSUE TITLE
EPUB Sürümü

### ISSUE THREAD

**Issue by maidis** [ogun/nebrinin-oglu#1]
Hem sizi hem de babanızı tebrik ederim. Kitabın sadece birkaç başlığını okudum henüz ama tamamını okumak için okuma listemde. Ben de birkaç yıl önce hem babama hem de anneme birer defter hediye ederek anılarını yazmalarını istemiştim, benzer bir kitap oluşturmak için. Annem çok az, babamsa epey bir yazdıktan sonra devamını getirmediler. Ben de pek sıkmadım sonrasında.

Şimdi bu kitabı onlara örnek olması için tavsiye etmek istiyorum. Bilgisayar veya telefon ekranından PDF dosyasını okumaları epey zor olacaktır, e-kitap okuyucuda epub olarak daha kolay okuyabilirler diye düşünüyorum.

Kitabın EPUB biçimli halini de yayımlama şansınız var mı?

**Comment by ogun** [comment]
Merhaba @maidis, güzel yorumlarınız için çok teşekkürler. Kindle üzerinde okumak için daha önce kendim için epub ve mobi versiyonlarına çevirmiştim zaten, onları da ekliyorum.

Umarım güzel bir örnek olur ve kitap yazmak için onlarda bir heyecan yaratır. Eğer kitap çıkarsa lütfen linkini benimle de paylaşın, okumak çok isterim.
